2025-03-05 15:02:56,081 - messaging - INFO - performance_logger.py:20 - LATENCY: rabbitmq_connection took 50.10ms
2025-03-05 15:02:56,083 - messaging - INFO - subscriber.py:81 - Successfully connected to RabbitMQ
2025-03-05 15:02:56,087 - messaging - INFO - subscriber.py:121 - Started consuming messages from RabbitMQ
2025-03-05 15:03:04,878 - messaging - INFO - subscriber.py:97 - Received move: {'from_square': 'g8', 'to_square': 'h6', 'message_id': '0e50e509', 'timestamp': 1741186984.875474}
2025-03-05 15:03:04,880 - messaging - INFO - performance_logger.py:20 - LATENCY: message_delivery took 4.59ms
2025-03-05 15:03:04,894 - messaging - INFO - subscriber.py:97 - Received move: {'from_square': 'f7', 'to_square': 'f5', 'message_id': 'f0dee4d3', 'timestamp': 1741186984.8765173}
2025-03-05 15:03:04,894 - messaging - INFO - performance_logger.py:20 - LATENCY: message_delivery took 18.05ms
2025-03-05 15:03:05,031 - messaging - INFO - performance_logger.py:31 - MOVE: g8h6 FAILURE
2025-03-05 15:03:05,034 - messaging - ERROR - performance_logger.py:35 - ERROR: movement - execution_failure: Move g8h6
2025-03-05 15:03:05,225 - messaging - INFO - performance_logger.py:31 - MOVE: f7f5 FAILURE (planning: 0.00ms, execution: 72.46ms)
2025-03-05 15:03:05,226 - messaging - ERROR - performance_logger.py:35 - ERROR: movement - execution_failure: Move f7f5
2025-03-05 15:05:46,999 - messaging - ERROR - subscriber.py:187 - Error during cleanup: Illegal close(200, 'Normal shutdown') request on <SelectConnection CLOSED transport=None params=<ConnectionParameters host=host.docker.internal port=5672 virtual_host=/ ssl=False>> because it was called while connection state=CLOSED.
2025-03-05 15:05:47,000 - messaging - ERROR - subscriber.py:125 - RabbitMQ consuming error: Stream connection lost: IndexError('pop from an empty deque')
